name: Update Hubble

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-hubble:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest Hubble version
        id: get_version
        run: |
          latest_version=$(curl -s https://api.github.com/repos/cilium/hubble/releases/latest | jq -r .tag_name)
          echo "Latest Hubble version: $latest_version"
          echo "version=$latest_version" >> $GITHUB_ENV

      - name: Get current Hubble version from Dockerfile
        id: get_current_version
        run: |
          current_version=$(grep -oP '(?<=ARG HUBBLE_VERSION=).*' controller/Dockerfile)
          echo "Current Hubble version: $current_version"
          echo "current_version=$current_version" >> $GITHUB_ENV

      - name: Check if update is needed
        id: check_update
        run: |
          if [ "${{ env.version }}" == "${{ env.current_version }}" ]; then
            echo "Hubble version is up to date. No update needed."
            echo "update_needed=false" >> $GITHUB_ENV
          else
            echo "Hubble version needs to be updated."
            echo "update_needed=true" >> $GITHUB_ENV
          fi

      - name: Update Dockerfile and Makefile with latest Hubble version
        if: env.update_needed == 'true'
        run: |
          sed -i "s/^ARG HUBBLE_VERSION=.*/ARG HUBBLE_VERSION=${{ env.version }}/" controller/Dockerfile
          sed -i "s/^ENV HUBBLE_VERSION=.*/ENV HUBBLE_VERSION=${{ env.version }}/" controller/Dockerfile
          sed -i "s/^HUBBLE_VERSION ?=.*/HUBBLE_VERSION=${{ env.version }}/" Makefile

      - name: Create new branch
        if: env.update_needed == 'true'
        run: |
          git checkout -b bump-hubble-version-${{ env.version }}

      - name: Commit and push changes
        if: env.update_needed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Bump Hubble version to ${{ env.version }}"
          git push --set-upstream origin bump-hubble-version-${{ env.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        if: env.update_needed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: bump-hubble-version-${{ env.version }}
          base: main
          title: "deps: bump Hubble version to ${{ env.version }}"
          body: "This PR bumps the Hubble version to ${{ env.version }}."
          labels: "area/dependencies"
          sign-commits: true
          signoff: true
